service: serverless-calendar

plugins:
  - serverless-dynamodb
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    EVENT_TABLE:
      Ref: 'events'
  region: eu-west-1


resources:
  Resources:
      events:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: 'events'
          AttributeDefinitions:
            - AttributeName: record_type
              AttributeType: S
            - AttributeName: id
              AttributeType: S
            - AttributeName: date_start
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: record_type
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          GlobalSecondaryIndexes:
            - IndexName: date_start_index
              KeySchema:
              - AttributeName: record_type
                KeyType: HASH
              - AttributeName: date_start
                KeyType: RANGE
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: '5'
                WriteCapacityUnits: '5'
functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
